/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientpatient;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Wiliam
 */
public class CheckValues extends javax.swing.JFrame {

     //String IP_ADDRESS = "localhost";
     String IP_ADDRESS = "192.168.0.8";
     int PATIENTID;
     int CONDITIONID;
     
    /**
     * Creates new form CheckValues
     */
    public CheckValues() {
        
         initComponents();
         //Set icon
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("heartImage.png")));
        
//get conditions to user
        List<String> conditions = new ArrayList<String>();
        conditions = getConditions();
        
        Iterator itrConditions = conditions.iterator();      
        //loop as many values there are on hte List
        while(itrConditions.hasNext()){
            cBoxConditions.addItem(itrConditions.next().toString());
        }   
            
    }
    
    //********************* get all the condition IDs in the DB *****************************************
    public List<String> getConditions(){
        //create an array list rto hold all of the ID's
        List<String> conditionsToReturn = new ArrayList<String>(); 
           try {
            //create the connection to MySQL server
            Connection con = DriverManager.getConnection("jdbc:mysql://" + IP_ADDRESS + ":3306/wiltech", "wilferraciolli", "160916");

            //create the Query
            String query = "SELECT * FROM conditions";

            //declare the statement and execute query
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
          
            //Iterate throught the returned values
            while (rs.next()) {               
                String conditionName = rs.getString("conditionName");
                conditionsToReturn.add(String.valueOf(conditionName));
            }//ends iterator
            st.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
            showMessageDialog(null, e.getMessage());
        }
        
        return conditionsToReturn;
    }//ends string get conditions

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblHeartBeat = new javax.swing.JLabel();
        lblBodyTemp = new javax.swing.JLabel();
        lblApnoea = new javax.swing.JLabel();
        lblFallOver = new javax.swing.JLabel();
        lblSweating = new javax.swing.JLabel();
        lblHeartAttack = new javax.swing.JLabel();
        lblIncontinence = new javax.swing.JLabel();
        lblRoomTemp = new javax.swing.JLabel();
        lblRoomHumidity = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        lblAirQuality = new javax.swing.JLabel();
        lblBreathing = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblAttack2 = new javax.swing.JLabel();
        lblAttack1 = new javax.swing.JLabel();
        lblAttack4 = new javax.swing.JLabel();
        lblAttack3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblApnoea2 = new javax.swing.JLabel();
        lblApnoea1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSensorName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtThreshold = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMin = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMax = new javax.swing.JTextArea();
        cBoxConditions = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        bckBlue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wearable Devices & Health Care Client");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 27, 739, 48);

        jPanel3.setLayout(null);

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Heart Beat");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(65, 77, 58, 16);

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Body Temp");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(65, 176, 62, 16);

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Apnoea");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(74, 283, 42, 16);

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Breathing");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(260, 80, 70, 16);

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Fall Over");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(260, 176, 48, 16);

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Incontinence");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(450, 290, 80, 16);

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("GPS");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(470, 170, 25, 16);

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Heart Attack");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(450, 80, 80, 16);

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Sweating");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(260, 290, 51, 16);

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Room Temp");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(640, 70, 69, 16);

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Room Humidity");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(628, 172, 85, 16);

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Air Quality");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(638, 286, 54, 16);

        lblHeartBeat.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblHeartBeat.setForeground(new java.awt.Color(102, 102, 102));
        lblHeartBeat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeartBeat.setText("N/A");
        jPanel3.add(lblHeartBeat);
        lblHeartBeat.setBounds(65, 18, 70, 47);

        lblBodyTemp.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblBodyTemp.setForeground(new java.awt.Color(102, 102, 102));
        lblBodyTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodyTemp.setText("N/A");
        jPanel3.add(lblBodyTemp);
        lblBodyTemp.setBounds(50, 120, 90, 47);

        lblApnoea.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblApnoea.setForeground(new java.awt.Color(102, 102, 102));
        lblApnoea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApnoea.setText("N/A");
        jPanel3.add(lblApnoea);
        lblApnoea.setBounds(58, 230, 80, 47);

        lblFallOver.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblFallOver.setForeground(new java.awt.Color(102, 102, 102));
        lblFallOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFallOver.setText("N/A");
        jPanel3.add(lblFallOver);
        lblFallOver.setBounds(250, 120, 70, 47);

        lblSweating.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblSweating.setForeground(new java.awt.Color(102, 102, 102));
        lblSweating.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSweating.setText("N/A");
        jPanel3.add(lblSweating);
        lblSweating.setBounds(250, 230, 70, 47);

        lblHeartAttack.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblHeartAttack.setForeground(new java.awt.Color(102, 102, 102));
        lblHeartAttack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeartAttack.setText("N/A");
        jPanel3.add(lblHeartAttack);
        lblHeartAttack.setBounds(449, 18, 70, 47);

        lblIncontinence.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblIncontinence.setForeground(new java.awt.Color(102, 102, 102));
        lblIncontinence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncontinence.setText("N/A");
        jPanel3.add(lblIncontinence);
        lblIncontinence.setBounds(438, 227, 80, 47);

        lblRoomTemp.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblRoomTemp.setForeground(new java.awt.Color(102, 102, 102));
        lblRoomTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomTemp.setText("N/A");
        jPanel3.add(lblRoomTemp);
        lblRoomTemp.setBounds(630, 20, 70, 47);

        lblRoomHumidity.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblRoomHumidity.setForeground(new java.awt.Color(102, 102, 102));
        lblRoomHumidity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomHumidity.setText("N/A");
        jPanel3.add(lblRoomHumidity);
        lblRoomHumidity.setBounds(638, 119, 70, 47);

        lblGPS.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblGPS.setForeground(new java.awt.Color(102, 102, 102));
        lblGPS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPS.setText("N/A");
        jPanel3.add(lblGPS);
        lblGPS.setBounds(449, 119, 59, 47);

        lblAirQuality.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblAirQuality.setForeground(new java.awt.Color(102, 102, 102));
        lblAirQuality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAirQuality.setText("N/A");
        jPanel3.add(lblAirQuality);
        lblAirQuality.setBounds(638, 233, 59, 47);

        lblBreathing.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblBreathing.setForeground(new java.awt.Color(102, 102, 102));
        lblBreathing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBreathing.setText("N/A");
        jPanel3.add(lblBreathing);
        lblBreathing.setBounds(240, 20, 80, 47);

        jTabbedPane1.addTab("Values", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 12))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Heart Attack"));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setText("Heart Beat");

        jLabel5.setText("Body Temp");

        jLabel4.setText("Sweating");

        jLabel23.setText("Breathing");

        lblAttack2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblAttack2.setForeground(new java.awt.Color(102, 102, 102));
        lblAttack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttack2.setText("N/A");

        lblAttack1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblAttack1.setForeground(new java.awt.Color(102, 102, 102));
        lblAttack1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttack1.setText("N/A");

        lblAttack4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblAttack4.setForeground(new java.awt.Color(102, 102, 102));
        lblAttack4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttack4.setText("N/A");

        lblAttack3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblAttack3.setForeground(new java.awt.Color(102, 102, 102));
        lblAttack3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttack3.setText("N/A");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAttack1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAttack3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAttack4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttack2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttack1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttack3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttack4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Apnoea"));

        jLabel24.setText("Breathing");

        jLabel25.setText("Noise");

        lblApnoea2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblApnoea2.setForeground(new java.awt.Color(102, 102, 102));
        lblApnoea2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApnoea2.setText("N/A");

        lblApnoea1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblApnoea1.setForeground(new java.awt.Color(102, 102, 102));
        lblApnoea1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApnoea1.setText("N/A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblApnoea2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblApnoea1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(156, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblApnoea2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lblApnoea1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Sensors", jPanel1);

        jLabel18.setText("Condition");

        jLabel19.setText("Sensors");

        jLabel20.setText("Threshold");

        jLabel21.setText("Minimum");

        jLabel22.setText("Maximum");

        txtSensorName.setColumns(1);
        txtSensorName.setRows(5);
        jScrollPane2.setViewportView(txtSensorName);

        txtThreshold.setColumns(1);
        txtThreshold.setRows(5);
        jScrollPane3.setViewportView(txtThreshold);

        txtMin.setColumns(1);
        txtMin.setRows(5);
        jScrollPane4.setViewportView(txtMin);

        txtMax.setColumns(1);
        txtMax.setRows(5);
        jScrollPane5.setViewportView(txtMax);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cBoxConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(122, 122, 122)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(8, 8, 8)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel21)))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel22)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxConditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conditions", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 120, 790, 351);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 100, 80, 16);

        txtUserName.setText("User 1");
        getContentPane().add(txtUserName);
        txtUserName.setBounds(610, 90, 80, 28);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh);
        btnRefresh.setBounds(690, 90, 72, 28);

        bckBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientpatient/bck.jpg"))); // NOI18N
        bckBlue.setText("jLabel6");
        getContentPane().add(bckBlue);
        bckBlue.setBounds(1, 0, 810, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       
        //Set the textBoxes to N/A
        lblHeartBeat.setText("N/A");
        lblBreathing.setText("N/A");  
        lblRoomTemp.setText("N/A");                
        lblBodyTemp.setText("N/A");
        lblFallOver.setText("N/A");
        lblGPS.setText("N/A");
        lblRoomHumidity.setText("N/A");
        lblApnoea.setText("N/A");
        lblSweating.setText("N/A");
        lblIncontinence.setText("N/A");
        lblAirQuality.setText("N/A");   
        lblApnoea1.setText("N/A");
        lblApnoea2.setText("N/A");
        lblAttack1.setText("N/A");
        lblAttack2.setText("N/A");
        lblAttack3.setText("N/A");
        lblAttack4.setText("N/A");
        
        //********************* Fill the sensor values ****************************
       try{
           
             //create the connection to MySQL server
            Connection con = DriverManager.getConnection("jdbc:mysql://" + IP_ADDRESS + ":3306/wiltech", "wilferraciolli", "160916");

            //create the Query
           String query = "SELECT sensorName, sensorDataValue, patientID FROM sensordata WHERE patientName='"+txtUserName.getText()+"'";
           
             //declare the statement and execute query
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            //Iterate throught the returned values
            while (rs.next()) {
                String sensorName = rs.getString("sensorName");
                String sensorDataValue = rs.getString("sensorDataValue");
                
                //set the text to the right value
                if(sensorName.equals("Heart Beat"))lblHeartBeat.setText(sensorDataValue);
                if(sensorName.equals("Breathing"))lblBreathing.setText(sensorDataValue);  
                if(sensorName.equals("Temp Room"))lblRoomTemp.setText(sensorDataValue);                
                if(sensorName.equals("Temp Body"))lblBodyTemp.setText(sensorDataValue);
                if(sensorName.equals("Accelerometer"))lblFallOver.setText(sensorDataValue);
                if(sensorName.equals("GPS"))lblGPS.setText(sensorDataValue);
                if(sensorName.equals("Humidity Room"))lblRoomHumidity.setText(sensorDataValue);
                if(sensorName.equals("Breathing"))lblApnoea.setText(sensorDataValue);
                if(sensorName.equals("Sweating"))lblSweating.setText(sensorDataValue);
                if(sensorName.equals("Moisture"))lblIncontinence.setText(sensorDataValue);
                if(sensorName.equals("Air Quality"))lblAirQuality.setText(sensorDataValue);  
                
                //get the patient ID
                PATIENTID = rs.getInt("patientID");
                //System.out.println(sensorName + sensorDataValue );
            }//ends iterator
            st.close();
            
        }catch (SQLException e){
              System.out.println(e.getMessage());
            showMessageDialog(null, e.getMessage());
        }
       
       //****************** Fill the conditions and sensors******************************
       try{
           //clear the values out
           txtSensorName.setText("");
           txtThreshold.setText("");
           txtMin.setText("");
           txtMax.setText("");
                
            //create the connection to MySQL server
            Connection con = DriverManager.getConnection("jdbc:mysql://" + IP_ADDRESS + ":3306/wiltech", "wilferraciolli", "160916");

            //create the Query
            String query = "SELECT conditionID FROM conditions WHERE conditionName= '"+cBoxConditions.getSelectedItem().toString()+"' ";

            //declare the statement and execute query
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            //get the condiition ID
            //Iterate throught the returned values
            while (rs.next()) {
                 CONDITIONID = rs.getInt("conditionID"); 
            }//ends iterator
            st.close();       
            
            //display the sensors and their threshold
            query = "SELECT * FROM conditionsensor WHERE conditionID= '"+CONDITIONID+"' ";

            //declare the statement and execute query
            st = con.createStatement();
            rs = st.executeQuery(query);
            
             //Iterate throught the returned values
            while (rs.next()) {               
                String sensorName = rs.getString("conditionSensor");
                String Threshold = rs.getString("conditionSensorThreshold");
                String min = rs.getString("conditionSensorMin");
                String max = rs.getString("conditionSensorMax");
                txtSensorName.append("\n" + sensorName );
                txtThreshold.append("\n" + Threshold);
                txtMin.append("\n" + min);
                txtMax.append("\n" + max);
            }//ends iterator
            st.close();
            
            
            //int patientID = rs.getInt("patientID");
            
            //query = "SELECT patientID FROM patients WHERE patientName= '"+txtUserName.getText()+"' ";

            //declare the statement and execute query
           // st = con.createStatement();
           // rs = st.executeQuery(query);
            
           
       }catch(SQLException e){
            System.out.println(e.getMessage());
            showMessageDialog(null, e.getMessage());
       }
       
       //********************** Fill in Medical conditions *********************
        try {
            //create the connection to MySQL server
            Connection con = DriverManager.getConnection("jdbc:mysql://"  + IP_ADDRESS + ":3306/wiltech", "wilferraciolli", "160916");

            //create the Query
            String query = "SELECT * FROM sensordata WHERE patientName='"+txtUserName.getText()+"'";

            //declare the statement and execute query
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
          
            //Iterate throught the returned values
            while (rs.next()) {
                String sensorName = rs.getString("sensorName");
                String sensorDataValue = rs.getString("sensorDataValue");
                
                //set the text to the right value
                if(sensorName.equals("Temp Body - Heart Attack"))lblAttack1.setText(sensorDataValue);
                if(sensorName.equals("Heart Beat - Heart Attack"))lblAttack2.setText(sensorDataValue);
                if(sensorName.equals("Sweating - Heart Attack"))lblAttack3.setText(sensorDataValue);
                if(sensorName.equals("Breathing - Heart Attack"))lblAttack4.setText(sensorDataValue);   
                
                if(sensorName.equals("Breathing"))lblApnoea1.setText(sensorDataValue); 
                if(sensorName.equals("Sound"))lblApnoea2.setText(sensorDataValue); 
                
            }//ends iterator
            st.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
            showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckValues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckBlue;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cBoxConditions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAirQuality;
    private javax.swing.JLabel lblApnoea;
    private javax.swing.JLabel lblApnoea1;
    private javax.swing.JLabel lblApnoea2;
    private javax.swing.JLabel lblAttack1;
    private javax.swing.JLabel lblAttack2;
    private javax.swing.JLabel lblAttack3;
    private javax.swing.JLabel lblAttack4;
    private javax.swing.JLabel lblBodyTemp;
    private javax.swing.JLabel lblBreathing;
    private javax.swing.JLabel lblFallOver;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblHeartAttack;
    private javax.swing.JLabel lblHeartBeat;
    private javax.swing.JLabel lblIncontinence;
    private javax.swing.JLabel lblRoomHumidity;
    private javax.swing.JLabel lblRoomTemp;
    private javax.swing.JLabel lblSweating;
    private javax.swing.JTextArea txtMax;
    private javax.swing.JTextArea txtMin;
    private javax.swing.JTextArea txtSensorName;
    private javax.swing.JTextArea txtThreshold;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
